/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.utsgui;

import javax.swing.JOptionPane;

/**
 *
 * @author D-7
 */
public class FrozenFood extends javax.swing.JFrame {
    
    /**
     * Creates new form FrozenFood
     */
    String nama,notelepon,alamat,pengemasan;
    public FrozenFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnamapemesan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxcireng = new javax.swing.JCheckBox();
        cbxtempura = new javax.swing.JCheckBox();
        cbxdimsum = new javax.swing.JCheckBox();
        cbxsosissapi = new javax.swing.JCheckBox();
        cbxnugget = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        cmbcireng = new javax.swing.JComboBox<>();
        btnkirim = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        txtnomortelepon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbsosissapi = new javax.swing.JComboBox<>();
        cmbnugget = new javax.swing.JComboBox<>();
        cmbtempura = new javax.swing.JComboBox<>();
        cmbdimsum = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PEMESANAN FROZEN FOOD");

        jLabel2.setText("NAMA PEMESAN");

        jLabel3.setText("LIST MAKANAN");

        cbxcireng.setText("Cireng~Rp 15.000");

        cbxtempura.setText("Tempura ~Rp 15.000");

        cbxdimsum.setText("Dimsum~Rp 20.000");
        cbxdimsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxdimsumActionPerformed(evt);
            }
        });

        cbxsosissapi.setText("Sosis Sapi~Rp 30.000");
        cbxsosissapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsosissapiActionPerformed(evt);
            }
        });

        cbxnugget.setText("Nugget~Rp 20.000");
        cbxnugget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnuggetActionPerformed(evt);
            }
        });

        jLabel6.setText("ALAMAT");

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        jLabel7.setText("PENGEMASAN TAMBAHAN");

        btngrup.add(jRadioButton1);
        jRadioButton1.setText("YA");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        btngrup.add(jRadioButton2);
        jRadioButton2.setText("TIDAK");

        cmbcireng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        btnkirim.setText("KIRIM");
        btnkirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkirimActionPerformed(evt);
            }
        });

        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jLabel8.setText("NOMOR TELEPON");

        cmbsosissapi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        cmbnugget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        cmbnugget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnuggetActionPerformed(evt);
            }
        });

        cmbtempura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        cmbdimsum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(29, 29, 29)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxsosissapi)
                                    .addComponent(cbxcireng)
                                    .addComponent(cbxnugget)
                                    .addComponent(cbxtempura)
                                    .addComponent(cbxdimsum)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmbdimsum, 0, 0, Short.MAX_VALUE)
                                            .addComponent(cmbtempura, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                            .addComponent(cmbcireng, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbsosissapi, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                            .addComponent(cmbnugget, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)))))
                            .addComponent(txtnamapemesan)
                            .addComponent(txtnomortelepon)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnkirim, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnamapemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbxcireng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbcireng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxsosissapi)
                .addGap(3, 3, 3)
                .addComponent(cmbsosissapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxnugget)
                .addGap(9, 9, 9)
                .addComponent(cmbnugget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxtempura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbtempura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxdimsum)
                .addGap(1, 1, 1)
                .addComponent(cmbdimsum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnomortelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(67, 67, 67)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkirim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxdimsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxdimsumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxdimsumActionPerformed

    private void cbxsosissapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsosissapiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxsosissapiActionPerformed

    private void cbxnuggetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnuggetActionPerformed
        // TODO add your handling code here: private void cbxdimsumActionPerformed(java.awt.event.ActionEvent evt) {                                          
   
    }//GEN-LAST:event_cbxnuggetActionPerformed

    private void btnkirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkirimActionPerformed
        // TODO add your handling code here:                                    
    String nama = txtnamapemesan.getText();
    String notelepon = txtnomortelepon.getText();
    String alamat = txtalamat.getText();
    String pengemasan = jRadioButton1.isSelected() ? "Ya" : "Tidak";

    // Memeriksa makanan yang dipilih
    StringBuilder pesanan = new StringBuilder();
    int totalHarga = 0;

    if (cbxcireng.isSelected()) {
        int jumlahCireng = Integer.parseInt(cmbcireng.getSelectedItem().toString());
        if (jumlahCireng > 0) {
            pesanan.append("- Cireng: ").append(jumlahCireng).append(" pcs\n");
            totalHarga += jumlahCireng * 15000;
        }
    }

    if (cbxsosissapi.isSelected()) {
        int jumlahSosis = Integer.parseInt(cmbsosissapi.getSelectedItem().toString());
        if (jumlahSosis > 0) {
            pesanan.append("- Sosis Sapi: ").append(jumlahSosis).append(" pcs\n");
            totalHarga += jumlahSosis * 30000;
        }
    }

    if (cbxnugget.isSelected()) {
        int jumlahNugget = Integer.parseInt(cmbnugget.getSelectedItem().toString());
        if (jumlahNugget > 0) {
            pesanan.append("- Nugget: ").append(jumlahNugget).append(" pcs\n");
            totalHarga += jumlahNugget * 20000;
        }
    }

    if (cbxtempura.isSelected()) {
        int jumlahTempura = Integer.parseInt(cmbtempura.getSelectedItem().toString());
        if (jumlahTempura > 0) {
            pesanan.append("- Tempura: ").append(jumlahTempura).append(" pcs\n");
            totalHarga += jumlahTempura * 15000;
        }
    }

    if (cbxdimsum.isSelected()) {
        int jumlahDimsum = Integer.parseInt(cmbdimsum.getSelectedItem().toString());
        if (jumlahDimsum > 0) {
            pesanan.append("- Dimsum: ").append(jumlahDimsum).append(" pcs\n");
            totalHarga += jumlahDimsum * 20000;
        }
    }

    // Validasi input
    if (nama.isEmpty() || notelepon.isEmpty() || alamat.isEmpty() || pesanan.length() == 0) {
        JOptionPane.showMessageDialog(this, "Harap lengkapi semua data dan periksa kembali pesanan anda!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    } else {
        // Menampilkan detail pesanan menggunakan JOptionPane
        String pesan = "Detail Pesanan:\n"
                + "Nama Pemesan: " + nama + "\n"
                + "Nomor Telepon: " + notelepon + "\n"
                + "Alamat: " + alamat + "\n"
                + "Pengemasan Tambahan: " + pengemasan + "\n\n"
                + "Pesanan:\n" + pesanan.toString()
                + "\nTotal Harga: Rp " + totalHarga;

        JOptionPane.showMessageDialog(this, pesan, "Konfirmasi Pesanan", JOptionPane.INFORMATION_MESSAGE);
    }   
         
    }//GEN-LAST:event_btnkirimActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtnamapemesan.setText("");
        cbxcireng.setText("");
        cbxsosissapi.setText("");
        cbxnugget.setText("");
        cbxtempura.setText("");
        cbxdimsum.setText("");
        cmbcireng.setSelectedItem("");
        cmbsosissapi.setSelectedItem("");
        cmbnugget.setSelectedItem("");
        cmbtempura.setSelectedItem("");
        cmbdimsum.setSelectedItem("");
        txtnomortelepon.setText("");
        txtalamat.setText("");
        btngrup.clearSelection();
    }//GEN-LAST:event_btnresetActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void cmbnuggetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnuggetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbnuggetActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0); // Menutup aplikasi
    }

    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrozenFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrozenFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrozenFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrozenFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrozenFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrup;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnkirim;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox cbxcireng;
    private javax.swing.JCheckBox cbxdimsum;
    private javax.swing.JCheckBox cbxnugget;
    private javax.swing.JCheckBox cbxsosissapi;
    private javax.swing.JCheckBox cbxtempura;
    private javax.swing.JComboBox<String> cmbcireng;
    private javax.swing.JComboBox<String> cmbdimsum;
    private javax.swing.JComboBox<String> cmbnugget;
    private javax.swing.JComboBox<String> cmbsosissapi;
    private javax.swing.JComboBox<String> cmbtempura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtnamapemesan;
    private javax.swing.JTextField txtnomortelepon;
    // End of variables declaration//GEN-END:variables
}
